package com.takin.emmet.string;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

abstract class Ascii {
    private Ascii() {
    }

    private static final Map<String, List<String>> inmap = new HashMap<>();

    static {
        inmap.put("0", Arrays.asList("°", "₀", "۰"));
        inmap.put("1", Arrays.asList("¹", "₁", "۱"));
        inmap.put("2", Arrays.asList("²", "₂", "۲"));
        inmap.put("3", Arrays.asList("³", "₃", "۳"));
        inmap.put("4", Arrays.asList("⁴", "₄", "۴", "٤"));
        inmap.put("5", Arrays.asList("⁵", "₅", "۵", "٥"));
        inmap.put("6", Arrays.asList("⁶", "₆", "۶", "٦"));
        inmap.put("7", Arrays.asList("⁷", "₇", "۷"));
        inmap.put("8", Arrays.asList("⁸", "₈", "۸"));
        inmap.put("9", Arrays.asList("⁹", "₉", "۹"));
        inmap.put("a", Arrays.asList("à", "á", "ả", "ã", "ạ", "ă", "ắ", "ằ", "ẳ", "ẵ", "ặ", "â", "ấ", "ầ", "ẩ", "ẫ", "ậ", "ā", "ą", "å", "α", "ά", "ἀ", "ἁ", "ἂ", "ἃ", "ἄ", "ἅ", "ἆ", "ἇ", "ᾀ", "ᾁ", "ᾂ", "ᾃ", "ᾄ", "ᾅ", "ᾆ", "ᾇ", "ὰ", "ά", "ᾰ", "ᾱ", "ᾲ", "ᾳ", "ᾴ", "ᾶ", "ᾷ", "а", "أ", "အ", "ာ", "ါ", "ǻ", "ǎ", "ª", "ა", "अ", "ا"));
        inmap.put("b", Arrays.asList("б", "β", "Ъ", "Ь", "ب", "ဗ", "ბ"));
        inmap.put("c", Arrays.asList("ç", "ć", "č", "ĉ", "ċ"));
        inmap.put("d", Arrays.asList("ď", "ð", "đ", "ƌ", "ȡ", "ɖ", "ɗ", "ᵭ", "ᶁ", "ᶑ", "д", "δ", "د", "ض", "ဍ", "ဒ", "დ"));
        inmap.put("e", Arrays.asList("é", "è", "ẻ", "ẽ", "ẹ", "ê", "ế", "ề", "ể", "ễ", "ệ", "ë", "ē", "ę", "ě", "ĕ", "ė", "ε", "έ", "ἐ", "ἑ", "ἒ", "ἓ", "ἔ", "ἕ", "ὲ", "έ", "е", "ё", "э", "є", "ə", "ဧ", "ေ", "ဲ", "ე", "ए", "إ", "ئ"));
        inmap.put("f", Arrays.asList("ф", "φ", "ف", "ƒ", "ფ"));
        inmap.put("g", Arrays.asList("ĝ", "ğ", "ġ", "ģ", "г", "ґ", "γ", "ဂ", "გ", "گ"));
        inmap.put("h", Arrays.asList("ĥ", "ħ", "η", "ή", "ح", "ه", "ဟ", "ှ", "ჰ"));
        inmap.put("i", Arrays.asList("í", "ì", "ỉ", "ĩ", "ị", "î", "ï", "ī", "ĭ", "į", "ı", "ι", "ί", "ϊ", "ΐ", "ἰ", "ἱ", "ἲ", "ἳ", "ἴ", "ἵ", "ἶ", "ἷ", "ὶ", "ί", "ῐ", "ῑ", "ῒ", "ΐ", "ῖ", "ῗ", "і", "ї", "и", "ဣ", "ိ", "ီ", "ည်", "ǐ", "ი", "इ", "ی"));
        inmap.put("j", Arrays.asList("ĵ", "ј", "Ј", "ჯ", "ج"));
        inmap.put("k", Arrays.asList("ķ", "ĸ", "к", "κ", "Ķ", "ق", "ك", "က", "კ", "ქ", "ک"));
        inmap.put("l", Arrays.asList("ł", "ľ", "ĺ", "ļ", "ŀ", "л", "λ", "ل", "လ", "ლ"));
        inmap.put("m", Arrays.asList("м", "μ", "م", "မ", "მ"));
        inmap.put("n", Arrays.asList("ñ", "ń", "ň", "ņ", "ŉ", "ŋ", "ν", "н", "ن", "န", "ნ"));
        inmap.put("o", Arrays.asList("ó", "ò", "ỏ", "õ", "ọ", "ô", "ố", "ồ", "ổ", "ỗ", "ộ", "ơ", "ớ", "ờ", "ở", "ỡ", "ợ", "ø", "ō", "ő", "ŏ", "ο", "ὀ", "ὁ", "ὂ", "ὃ", "ὄ", "ὅ", "ὸ", "ό", "о", "و", "θ", "ို", "ǒ", "ǿ", "º", "ო", "ओ"));
        inmap.put("p", Arrays.asList("п", "π", "ပ", "პ", "پ"));
        inmap.put("q", Arrays.asList("ყ"));
        inmap.put("r", Arrays.asList("ŕ", "ř", "ŗ", "р", "ρ", "ر", "რ"));
        inmap.put("s", Arrays.asList("ś", "š", "ş", "с", "σ", "ș", "ς", "س", "ص", "စ", "ſ", "ს"));
        inmap.put("t", Arrays.asList("ť", "ţ", "т", "τ", "ț", "ت", "ط", "ဋ", "တ", "ŧ", "თ", "ტ"));
        inmap.put("u", Arrays.asList("ú", "ù", "ủ", "ũ", "ụ", "ư", "ứ", "ừ", "ử", "ữ", "ự", "û", "ū", "ů", "ű", "ŭ", "ų", "µ", "у", "ဉ", "ု", "ူ", "ǔ", "ǖ", "ǘ", "ǚ", "ǜ", "უ", "उ"));
        inmap.put("v", Arrays.asList("в", "ვ", "ϐ"));
        inmap.put("w", Arrays.asList("ŵ", "ω", "ώ", "ဝ", "ွ"));
        inmap.put("x", Arrays.asList("χ", "ξ"));
        inmap.put("y", Arrays.asList("ý", "ỳ", "ỷ", "ỹ", "ỵ", "ÿ", "ŷ", "й", "ы", "υ", "ϋ", "ύ", "ΰ", "ي", "ယ"));
        inmap.put("z", Arrays.asList("ź", "ž", "ż", "з", "ζ", "ز", "ဇ", "ზ"));
        inmap.put("aa", Arrays.asList("ع", "आ", "آ"));
        inmap.put("ae", Arrays.asList("ä", "æ", "ǽ"));
        inmap.put("ai", Arrays.asList("ऐ"));
        inmap.put("at", Arrays.asList("@"));
        inmap.put("ch", Arrays.asList("ч", "ჩ", "ჭ", "چ"));
        inmap.put("dj", Arrays.asList("ђ", "đ"));
        inmap.put("dz", Arrays.asList("џ", "ძ"));
        inmap.put("ei", Arrays.asList("ऍ"));
        inmap.put("gh", Arrays.asList("غ", "ღ"));
        inmap.put("ii", Arrays.asList("ई"));
        inmap.put("ij", Arrays.asList("ĳ"));
        inmap.put("kh", Arrays.asList("х", "خ", "ხ"));
        inmap.put("lj", Arrays.asList("љ"));
        inmap.put("nj", Arrays.asList("њ"));
        inmap.put("oe", Arrays.asList("ö", "œ", "ؤ"));
        inmap.put("oi", Arrays.asList("ऑ"));
        inmap.put("oii", Arrays.asList("ऒ"));
        inmap.put("ps", Arrays.asList("ψ"));
        inmap.put("sh", Arrays.asList("ш", "შ", "ش"));
        inmap.put("shch", Arrays.asList("щ"));
        inmap.put("ss", Arrays.asList("ß"));
        inmap.put("sx", Arrays.asList("ŝ"));
        inmap.put("th", Arrays.asList("þ", "ϑ", "ث", "ذ", "ظ"));
        inmap.put("ts", Arrays.asList("ц", "ც", "წ"));
        inmap.put("ue", Arrays.asList("ü"));
        inmap.put("uu", Arrays.asList("ऊ"));
        inmap.put("ya", Arrays.asList("я"));
        inmap.put("yu", Arrays.asList("ю"));
        inmap.put("zh", Arrays.asList("ж", "ჟ", "ژ"));
        inmap.put("(c)", Arrays.asList("©"));
        inmap.put("A", Arrays.asList("Á", "À", "Ả", "Ã", "Ạ", "Ă", "Ắ", "Ằ", "Ẳ", "Ẵ", "Ặ", "Â", "Ấ", "Ầ", "Ẩ", "Ẫ", "Ậ", "Å", "Ā", "Ą", "Α", "Ά", "Ἀ", "Ἁ", "Ἂ", "Ἃ", "Ἄ", "Ἅ", "Ἆ", "Ἇ", "ᾈ", "ᾉ", "ᾊ", "ᾋ", "ᾌ", "ᾍ", "ᾎ", "ᾏ", "Ᾰ", "Ᾱ", "Ὰ", "Ά", "ᾼ", "А", "Ǻ", "Ǎ"));
        inmap.put("B", Arrays.asList("Б", "Β", "ब"));
        inmap.put("C", Arrays.asList("Ç", "Ć", "Č", "Ĉ", "Ċ"));
        inmap.put("D", Arrays.asList("Ď", "Ð", "Đ", "Ɖ", "Ɗ", "Ƌ", "ᴅ", "ᴆ", "Д", "Δ"));
        inmap.put("E", Arrays.asList("É", "È", "Ẻ", "Ẽ", "Ẹ", "Ê", "Ế", "Ề", "Ể", "Ễ", "Ệ", "Ë", "Ē", "Ę", "Ě", "Ĕ", "Ė", "Ε", "Έ", "Ἐ", "Ἑ", "Ἒ", "Ἓ", "Ἔ", "Ἕ", "Έ", "Ὲ", "Е", "Ё", "Э", "Є", "Ə"));
        inmap.put("F", Arrays.asList("Ф", "Φ"));
        inmap.put("G", Arrays.asList("Ğ", "Ġ", "Ģ", "Г", "Ґ", "Γ"));
        inmap.put("H", Arrays.asList("Η", "Ή", "Ħ"));
        inmap.put("I", Arrays.asList("Í", "Ì", "Ỉ", "Ĩ", "Ị", "Î", "Ï", "Ī", "Ĭ", "Į", "İ", "Ι", "Ί", "Ϊ", "Ἰ", "Ἱ", "Ἳ", "Ἴ", "Ἵ", "Ἶ", "Ἷ", "Ῐ", "Ῑ", "Ὶ", "Ί", "И", "І", "Ї", "Ǐ", "ϒ"));
        inmap.put("K", Arrays.asList("К", "Κ"));
        inmap.put("L", Arrays.asList("Ĺ", "Ł", "Л", "Λ", "Ļ", "Ľ", "Ŀ", "ल"));
        inmap.put("M", Arrays.asList("М", "Μ"));
        inmap.put("N", Arrays.asList("Ń", "Ñ", "Ň", "Ņ", "Ŋ", "Н", "Ν"));
        inmap.put("O", Arrays.asList("Ó", "Ò", "Ỏ", "Õ", "Ọ", "Ô", "Ố", "Ồ", "Ổ", "Ỗ", "Ộ", "Ơ", "Ớ", "Ờ", "Ở", "Ỡ", "Ợ", "Ø", "Ō", "Ő", "Ŏ", "Ο", "Ό", "Ὀ", "Ὁ", "Ὂ", "Ὃ", "Ὄ", "Ὅ", "Ὸ", "Ό", "О", "Θ", "Ө", "Ǒ", "Ǿ"));
        inmap.put("P", Arrays.asList("П", "Π"));
        inmap.put("R", Arrays.asList("Ř", "Ŕ", "Р", "Ρ", "Ŗ"));
        inmap.put("S", Arrays.asList("Ş", "Ŝ", "Ș", "Š", "Ś", "С", "Σ"));
        inmap.put("T", Arrays.asList("Ť", "Ţ", "Ŧ", "Ț", "Т", "Τ"));
        inmap.put("U", Arrays.asList("Ú", "Ù", "Ủ", "Ũ", "Ụ", "Ư", "Ứ", "Ừ", "Ử", "Ữ", "Ự", "Û", "Ū", "Ů", "Ű", "Ŭ", "Ų", "У", "Ǔ", "Ǖ", "Ǘ", "Ǚ", "Ǜ"));
        inmap.put("V", Arrays.asList("В"));
        inmap.put("W", Arrays.asList("Ω", "Ώ", "Ŵ"));
        inmap.put("X", Arrays.asList("Χ", "Ξ"));
        inmap.put("Y", Arrays.asList("Ý", "Ỳ", "Ỷ", "Ỹ", "Ỵ", "Ÿ", "Ῠ", "Ῡ", "Ὺ", "Ύ", "Ы", "Й", "Υ", "Ϋ", "Ŷ"));
        inmap.put("Z", Arrays.asList("Ź", "Ž", "Ż", "З", "Ζ"));
        inmap.put("AE", Arrays.asList("Ä", "Æ", "Ǽ"));
        inmap.put("CH", Arrays.asList("Ч"));
        inmap.put("DJ", Arrays.asList("Ђ"));
        inmap.put("DZ", Arrays.asList("Џ"));
        inmap.put("GX", Arrays.asList("Ĝ"));
        inmap.put("HX", Arrays.asList("Ĥ"));
        inmap.put("IJ", Arrays.asList("Ĳ"));
        inmap.put("JX", Arrays.asList("Ĵ"));
        inmap.put("KH", Arrays.asList("Х"));
        inmap.put("LJ", Arrays.asList("Љ"));
        inmap.put("NJ", Arrays.asList("Њ"));
        inmap.put("OE", Arrays.asList("Ö", "Œ"));
        inmap.put("PS", Arrays.asList("Ψ"));
        inmap.put("SH", Arrays.asList("Ш"));
        inmap.put("SHCH", Arrays.asList("Щ"));
        inmap.put("SS", Arrays.asList("ẞ"));
        inmap.put("TH", Arrays.asList("Þ"));
        inmap.put("TS", Arrays.asList("Ц"));
        inmap.put("UE", Arrays.asList("Ü"));
        inmap.put("YA", Arrays.asList("Я"));
        inmap.put("YU", Arrays.asList("Ю"));
        inmap.put("ZH", Arrays.asList("Ж"));
        inmap.put(" ", Arrays.asList("\\xC2\\xA0", "\\xE2\\x80\\x80", "\\xE2\\x80\\x81", "\\xE2\\x80\\x82", "\\xE2\\x80\\x83", "\\xE2\\x80\\x84", "\\xE2\\x80\\x85", "\\xE2\\x80\\x86", "\\xE2\\x80\\x87", "\\xE2\\x80\\x88", "\\xE2\\x80\\x89", "\\xE2\\x80\\x8A", "\\xE2\\x80\\xAF", "\\xE2\\x81\\x9F", "\\xE3\\x80\\x80"));

    }

}
